const vocabData = {
    "Level 1": [
        { word: "设施", pinyin: "shè shī", meaning: "facilities" },
        { word: "技能", pinyin: "jì néng", meaning: "skill; ability" },
        { word: "别扭", pinyin: "biè niu", meaning: "awkward; uncomfortable" },
        { word: "冤枉", pinyin: "yuān wang", meaning: "to accuse wrongly; treated unjustly" },
        { word: "锻炼", pinyin: "duàn liàn", meaning: "to exercise; to train" },
        { word: "达人", pinyin: "dá rén", meaning: "expert; specialist" },
        { word: "科技", pinyin: "kē jì", meaning: "science and technology" },
        { word: "口头禅", pinyin: "kǒu tóu chán", meaning: "catchphrase; mantra" },
        { word: "小事一桩", pinyin: "xiǎo shì yī zhuāng", meaning: "a piece of cake" },
        { word: "人缘", pinyin: "rén yuán", meaning: "relations with other people" },
        { word: "推荐", pinyin: "tuī jiàn", meaning: "to recommend" },
        { word: "惹麻烦", pinyin: "rě má fan", meaning: "to cause trouble" },

        { word: "习俗", pinyin: "xí sú", meaning: "custom; tradition" },
        { word: "辞旧迎新", pinyin: "cí jiù yíng xīn", meaning: "ring out the old and ring in the new" },
        { word: "玻璃", pinyin: "bō li", meaning: "glass" },
        { word: "柑", pinyin: "gān", meaning: "mandarin orange" },
        { word: "除夕", pinyin: "chú xī", meaning: "Chinese New Year's Eve" },
        { word: "财富", pinyin: "cái fù", meaning: "wealth; riches" },

        { word: "博物馆", pinyin: "bó wù guǎn", meaning: "museum" },
        { word: "收藏", pinyin: "shōu cáng", meaning: "to collect; collection" },
        { word: "建筑", pinyin: "jiàn zhù", meaning: "building; architecture" },
        { word: "巴刹", pinyin: "bā shā", meaning: "wet market" },
        { word: "售卖", pinyin: "shòu mài", meaning: "to sell" },
        { word: "皇宫", pinyin: "huáng gōng", meaning: "imperial palace" },
        { word: "城堡", pinyin: "chéng bǎo", meaning: "castle" },
        { word: "魅力", pinyin: "mèi lì", meaning: "charm; charisma" },
        { word: "流连忘返", pinyin: "liú lián wàng fǎn", meaning: "linger and forget to go home" },
        { word: "平均", pinyin: "píng jūn", meaning: "average" },
        { word: "繁忙", pinyin: "fán máng", meaning: "busy; bustling" },
        { word: "载客量", pinyin: "zài kè liàng", meaning: "passenger capacity" },
        { word: "娱乐", pinyin: "yú lè", meaning: "entertainment" },
        { word: "文化", pinyin: "wén huà", meaning: "culture" },

        { word: "坚持不懈", pinyin: "jiān chí bù xiè", meaning: "persevere unremittingly" },
        { word: "诺言", pinyin: "nuò yán", meaning: "promise" },
        { word: "工作坊", pinyin: "gōng zuò fāng", meaning: "workshop" },
        { word: "维护", pinyin: "wéi hù", meaning: "safeguard; maintain" },
        { word: "友谊", pinyin: "yǒu yì", meaning: "friendship" },
        { word: "一帆风顺", pinyin: "yī fān fēng shùn", meaning: "smooth sailing" },
        { word: "有效", pinyin: "yǒu xiào", meaning: "effective; valid" },
        { word: "策略", pinyin: "cè lüè", meaning: "strategy" },
        { word: "嘉宾", pinyin: "jiā bīn", meaning: "esteemed guest" },
        { word: "辅导员", pinyin: "fǔ dǎo yuán", meaning: "counsellor" },
        { word: "言出必行", pinyin: "yán chū bì xíng", meaning: "to keep one's word" },
        { word: "以礼待人", pinyin: "yǐ lǐ dài rén", meaning: "treat with courtesy" },
        { word: "起码", pinyin: "qǐ mǎ", meaning: "at least; minimum" },

        { word: "剩", pinyin: "shèng", meaning: "remain; left" },
        { word: "牙膏", pinyin: "yá gāo", meaning: "toothpaste" },
        { word: "橡皮擦", pinyin: "xiàng pí cā", meaning: "eraser" },
        { word: "薯条", pinyin: "shǔ tiáo", meaning: "french fries" },
        { word: "番茄酱", pinyin: "fān qié jiàng", meaning: "ketchup" },
        { word: "奖励", pinyin: "jiǎng lì", meaning: "reward" },
        { word: "获得", pinyin: "huò dé", meaning: "obtain; receive" },
        { word: "企业", pinyin: "qǐ yè", meaning: "enterprise; company" },
        { word: "创新", pinyin: "chuàng xīn", meaning: "innovation; to innovate" },

        { word: "油漆", pinyin: "yóu qī", meaning: "paint; lacquer" },
        { word: "栏杆", pinyin: "lán gān", meaning: "railing" },
        { word: "宿舍", pinyin: "sù shè", meaning: "dormitory" },
        { word: "凭", pinyin: "píng", meaning: "rely on" },
        { word: "订购", pinyin: "dìng gòu", meaning: "place an order" },
        { word: "塔台", pinyin: "tǎ tái", meaning: "control tower" },
        { word: "范围", pinyin: "fàn wéi", meaning: "range; scope" },
        { word: "警惕", pinyin: "jǐng tì", meaning: "vigilant; alert" },
        { word: "一旦", pinyin: "yī dàn", meaning: "once; in case" },
        { word: "失误", pinyin: "shī wù", meaning: "mistake" },
        { word: "不堪设想", pinyin: "bù kān shè xiǎng", meaning: "too horrible to contemplate" },
        { word: "及时", pinyin: "jí shí", meaning: "timely; in time" },
        { word: "心满意足", pinyin: "xīn mǎn yì zú", meaning: "perfectly contented; satisfied" },

        { word: "培养", pinyin: "péi yǎng", meaning: "to cultivate; to develop" },
        { word: "兴致勃勃", pinyin: "xìng zhì bó bó", meaning: "in high spirits; full of zest" },
        { word: "粘", pinyin: "zhān", meaning: "to glue; to paste; to stick to" },
        { word: "蛋液", pinyin: "dàn yè", meaning: "liquid of the egg" },
        { word: "狼狈", pinyin: "láng bèi", meaning: "in a difficult situation" },
        { word: "赌气", pinyin: "dǔ qì", meaning: "to act in a fit of pique" },
        { word: "小心翼翼", pinyin: "xiǎo xīn yì yì", meaning: "very carefully; prudent" },
        { word: "证明", pinyin: "zhèng míng", meaning: "to prove; proof" },
        { word: "捣乱", pinyin: "dǎo luàn", meaning: "to disturb; look for trouble" },
        { word: "荧光笔", pinyin: "yíng guāng bǐ", meaning: "highlighter" },
        { word: "抵挡", pinyin: "dǐ dǎng", meaning: "to resist; to ward off" },
        { word: "拉扯", pinyin: "lā che", meaning: "to drag; to pull; to raise a child" },
        { word: "手足无措", pinyin: "shǒu zú wú cuò", meaning: "at a loss to know what to do" },
        { word: "安慰", pinyin: "ān wèi", meaning: "to comfort; consolation" },
        { word: "布置", pinyin: "bù zhì", meaning: "to arrange; to assign" },
        { word: "随身", pinyin: "suí shēn", meaning: "to carry with oneself" },
        { word: "引起", pinyin: "yǐn qǐ", meaning: "to cause; to arouse" },

        { word: "忙碌", pinyin: "máng lù", meaning: "busy; bustling" },
        { word: "装饰", pinyin: "zhuāng shì", meaning: "to decorate" },
        { word: "结婚", pinyin: "jié hūn", meaning: "to marry" },
        { word: "嫁", pinyin: "jià", meaning: "to marry (of a woman)" },
        { word: "匆匆", pinyin: "cōng cōng", meaning: "hurriedly; hastily" },
        { word: "碗碟", pinyin: "wǎn dié", meaning: "bowls and plates" },
        { word: "渐渐", pinyin: "jiàn jiàn", meaning: "gradually" },
        { word: "热腾腾", pinyin: "rè téng téng", meaning: "steaming hot" },
        { word: "象征", pinyin: "xiàng zhēng", meaning: "emblem; symbol" },
        { word: "围炉", pinyin: "wéi lú", meaning: "steamboat" },
        { word: "叽叽喳喳", pinyin: "jī jī zhā zhā", meaning: "chirp; chatter" },
        { word: "悦耳", pinyin: "yuè ěr", meaning: "sweet-sounding" },
        { word: "视讯", pinyin: "shì xùn", meaning: "video call" },
        { word: "期待", pinyin: "qī dài", meaning: "to look forward to; expectation" },

        { word: "横梁", pinyin: "héng liáng", meaning: "crossbeam" },
        { word: "覆盖", pinyin: "fù gài", meaning: "to cover" },
        { word: "瀑布", pinyin: "pù bù", meaning: "waterfall" },
        { word: "蹦跳", pinyin: "bèng tiào", meaning: "to hop; jump" },
        { word: "甚至", pinyin: "shèn zhì", meaning: "even" },
        { word: "刺激", pinyin: "cì jī", meaning: "exciting; to stimulate" },
        { word: "迷宫", pinyin: "mí gōng", meaning: "maze; labyrinth" },

        { word: "早晨", pinyin: "zǎo chén", meaning: "early morning" },
        { word: "赖床", pinyin: "lài chuáng", meaning: "dawdle in bed" },
        { word: "滋味", pinyin: "zī wèi", meaning: "taste; flavor; feeling" },
        { word: "催促", pinyin: "cuī cù", meaning: "to urge" },
        { word: "哀求", pinyin: "āi qiú", meaning: "to plead" },
        { word: "硬着头皮", pinyin: "yìng zhe tou pí", meaning: "brace oneself to do something" },
        { word: "藤鞭", pinyin: "téng biān", meaning: "rattan cane" },
        { word: "挨打", pinyin: "ái dǎ", meaning: "take a beating" },
        { word: "混合", pinyin: "hùn hé", meaning: "to mix; mixture" },
        { word: "女佣", pinyin: "nǚ yōng", meaning: "maid" },
        { word: "嗓子眼", pinyin: "sǎng zi yǎn", meaning: "throat" },
        { word: "允许", pinyin: "yǔn xǔ", meaning: "permit; allow" },
        { word: "毛病", pinyin: "máo bìng", meaning: "fault; problem; bad habit" },
        { word: "逃学", pinyin: "táo xué", meaning: "to play truant; skip school" },
        { word: "居然", pinyin: "jū rán", meaning: "unexpectedly; actually" },

        { word: "牧场", pinyin: "mù chǎng", meaning: "pasture; ranch" },
        { word: "潜水", pinyin: "qián shuǐ", meaning: "to dive" },
        { word: "降落", pinyin: "jiàng luò", meaning: "to land; to descend" },
        { word: "屁股", pinyin: "pì gǔ", meaning: "buttocks" },
        { word: "翘", pinyin: "qiào", meaning: "stick up; tilt" },
        { word: "照耀", pinyin: "zhào yào", meaning: "to shine on; illuminate" },
        { word: "副", pinyin: "fù", meaning: "classifier for facial expressions" },
        { word: "浑身", pinyin: "hún shēn", meaning: "all over the body" },
        { word: "基因", pinyin: "jī yīn", meaning: "gene" },
        { word: "手势", pinyin: "shǒu shì", meaning: "gesture" },
        { word: "立即", pinyin: "lì jí", meaning: "immediately; at once" },
        { word: "腾空而起", pinyin: "téng kōng ér qǐ", meaning: "to rise into the air" },
        { word: "打量", pinyin: "dǎ liang", meaning: "to size up; to look over" },

        { word: "贡献", pinyin: "gòng xiàn", meaning: "contribute; contribution" },
        { word: "行驶", pinyin: "xíng shǐ", meaning: "travel; drive a vehicle" },
        { word: "延误", pinyin: "yán wu", meaning: "delay" },
        { word: "确保", pinyin: "què bǎo", meaning: "to ensure; to guarantee" },
        { word: "轨道", pinyin: "guǐ dào", meaning: "track; orbit" },
        { word: "凌晨", pinyin: "líng chén", meaning: "early morning" },
        { word: "就绪", pinyin: "jiù xù", meaning: "ready; in order" },
        { word: "裂痕", pinyin: "liè hén", meaning: "crack; split" },
        { word: "顺畅", pinyin: "shùn chàng", meaning: "fluent; smooth" },
        { word: "全力以赴", pinyin: "quán lì yǐ fù", meaning: "all-out effort" },
        { word: "职业", pinyin: "zhí yè", meaning: "occupation; profession" },
        { word: "故障", pinyin: "gù zhàng", meaning: "malfunction; fault" },
        { word: "幕后", pinyin: "mù hòu", meaning: "behind the scenes" },
        { word: "默默无闻", pinyin: "mò mò wú wén", meaning: "unknown; obscure; quietly working without fame" },
        { word: "维修", pinyin: "wéi xiū", meaning: "maintenance; repair" },

        { word: "究竟", pinyin: "jiū jìng", meaning: "after all; exactly" },
        { word: "虚惊一场", pinyin: "xū jīng yī chǎng", meaning: "a false alarm" },
        { word: "壮胆", pinyin: "zhuàng dǎn", meaning: "to bolster one's courage" },
        { word: "处理", pinyin: "chǔ lǐ", meaning: "to handle; to deal with" },
        { word: "关怀", pinyin: "guān huái", meaning: "care; concern" },

        { word: "红枣", pinyin: "hóng zǎo", meaning: "red date" },
        { word: "大吉大利", pinyin: "dà jí dà lì", meaning: "great luck and great prosperity" },
        { word: "疼爱", pinyin: "téng ài", meaning: "to love dearly" },
        { word: "儿媳妇", pinyin: "ér xí fu", meaning: "daughter-in-law" },
        { word: "感激", pinyin: "gǎn jī", meaning: "grateful; thankful" },
        { word: "莫名其妙", pinyin: "mò míng qí miào", meaning: "inexplicable; baffling" },
        { word: "疑惑", pinyin: "yí huò", meaning: "suspicion; to puzzle over" },
        { word: "喜悦", pinyin: "xǐ yuè", meaning: "joy; delight" },
        { word: "亲切", pinyin: "qīn qiè", meaning: "kind; friendly" },

        { word: "栏", pinyin: "lán", meaning: "fence; railing" },
        { word: "棕色", pinyin: "zōng sè", meaning: "brown" },
        { word: "氧化", pinyin: "yǎng huà", meaning: "oxidize" },
        { word: "即", pinyin: "jí", meaning: "namely; that is; immediately" },
        { word: "陌生", pinyin: "mò shēng", meaning: "strange; unfamiliar" },
        { word: "同胞", pinyin: "tóng bāo", meaning: "fellow citizen; compatriot" },
        { word: "宁静", pinyin: "níng jìng", meaning: "tranquil" },
        { word: "属于", pinyin: "shǔ yú", meaning: "belong to" },
        { word: "场景", pinyin: "chǎng jǐng", meaning: "scene; setting" },
        { word: "秘密", pinyin: "mì mì", meaning: "secret" },

        { word: "相貌", pinyin: "xiàng mào", meaning: "appearance" },
        { word: "何必", pinyin: "hé bì", meaning: "why should; no need" },
        { word: "记账", pinyin: "jì zhàng", meaning: "bookkeeping" },
        { word: "亏", pinyin: "kuī", meaning: "deficit; deficiency" },
        { word: "撇", pinyin: "piē", meaning: "to cast away" },
        { word: "起航", pinyin: "qǐ háng", meaning: "set sail; take off" },
        { word: "治病", pinyin: "zhì bìng", meaning: "to treat an illness" },

        { word: "伤脑筋", pinyin: "shāng nǎo jīn", meaning: "real headache" },
        { word: "中央", pinyin: "zhōng yāng", meaning: "central" },
        { word: "华侨", pinyin: "huá qiáo", meaning: "overseas Chinese" },
        { word: "摩天大楼", pinyin: "mó tiān dà lóu", meaning: "skyscraper" },
        { word: "薄薄的", pinyin: "báo báo de", meaning: "thin" },
        { word: "打交道", pinyin: "dǎ jiāo dào", meaning: "to deal with; to interact with" },

        { word: "隔壁", pinyin: "gé bì", meaning: "next door" },
        { word: "稳定", pinyin: "wěn dìng", meaning: "steady; stable" },
        { word: "光芒", pinyin: "guāng máng", meaning: "rays of light" },
        { word: "悠闲", pinyin: "yōu xián", meaning: "leisurely; carefree" },
        { word: "一辈子", pinyin: "yī bèi zi", meaning: "a lifetime; one's whole life" },
        { word: "奉献", pinyin: "fèng xiàn", meaning: "dedicate; devote" }
    ],

"Level 2": [
    { word: "教训", pinyin: "jiào xun", meaning: "lesson; to lecture somebody" },
    { word: "叛逆", pinyin: "pàn nì", meaning: "to rebel; a rebel" },
    { word: "委屈", pinyin: "wěi qu", meaning: "to feel wronged; grievance" },
    { word: "内疚", pinyin: "nèi jiù", meaning: "guilty conscience; feel guilt" },
    { word: "不妨", pinyin: "bù fáng", meaning: "might as well" },
    { word: "监督", pinyin: "jiān dū", meaning: "to supervise; control" },
    { word: "代沟", pinyin: "dài gōu", meaning: "generation gap" },
    { word: "上瘾", pinyin: "shàng yǐn", meaning: "to become addicted" },
    { word: "疏远", pinyin: "shū yuǎn", meaning: "to drift apart; estranged" },
    { word: "迎刃而解", pinyin: "yíng rèn ér jiě", meaning: "to be readily solved" },
    { word: "体谅", pinyin: "tǐ liàng", meaning: "to empathize; show understanding" },

    { word: "捐款", pinyin: "juān kuǎn", meaning: "to donate money" },
    { word: "医疗", pinyin: "yī liáo", meaning: "medical treatment" },
    { word: "友善", pinyin: "yǒu shàn", meaning: "friendly; kind" },
    { word: "斑纹", pinyin: "bān wén", meaning: "stripes; markings" },
    { word: "辨识", pinyin: "biàn shí", meaning: "to identify; distinguish" },
    { word: "害羞", pinyin: "hài xiū", meaning: "shy; bashful" },
    { word: "馋", pinyin: "chán", meaning: "greedy for food; gluttonous" },
    { word: "摔跤", pinyin: "shuāi jiāo", meaning: "to fall down; wrestling" },
    { word: "葡萄", pinyin: "pú tao", meaning: "grape" },
    { word: "凶猛", pinyin: "xiōng měng", meaning: "fierce; violent" },
    { word: "独一无二", pinyin: "dú yī wú èr", meaning: "unique and unmatched" },
    { word: "调皮", pinyin: "tiáo pí", meaning: "naughty; mischievous" },

    { word: "因素", pinyin: "yīn sù", meaning: "factor; element" },
    { word: "水喉", pinyin: "shuǐ hóu", meaning: "water tap" },
    { word: "资源", pinyin: "zī yuán", meaning: "resources" },
    { word: "艰巨", pinyin: "jiān jù", meaning: "arduous; difficult" },
    { word: "昂贵", pinyin: "áng guì", meaning: "expensive" },
    { word: "消耗", pinyin: "xiāo hào", meaning: "to consume; consumption" },
    { word: "干旱", pinyin: "gān hàn", meaning: "drought" },
    { word: "扩大", pinyin: "kuò dà", meaning: "to expand" },
    { word: "蓄水池", pinyin: "xù shuǐ chí", meaning: "reservoir" },
    { word: "浴室", pinyin: "yù shì", meaning: "bathroom" },
    { word: "洗澡", pinyin: "xǐ zǎo", meaning: "to bathe" },
    { word: "趋势", pinyin: "qū shì", meaning: "trend; tendency" },

    { word: "身材", pinyin: "shēn cái", meaning: "figure; stature" },
    { word: "自卑", pinyin: "zì bēi", meaning: "inferiority complex; self-abased" },
    { word: "羡慕", pinyin: "xiàn mù", meaning: "to envy; admire" },
    { word: "抗拒", pinyin: "kàng jù", meaning: "to resist; reject" },
    { word: "诱惑", pinyin: "yòu huò", meaning: "temptation" },
    { word: "毅力", pinyin: "yì lì", meaning: "perseverance; willpower" },
    { word: "戒", pinyin: "jiè", meaning: "to quit; guard against" },
    { word: "瞌睡", pinyin: "kē shuì", meaning: "drowsy; sleepy" },
    { word: "烹饪", pinyin: "pēng rèn", meaning: "cooking" },
    { word: "选修", pinyin: "xuǎn xiū", meaning: "elective (subject)" },

    { word: "简陋", pinyin: "jiǎn lòu", meaning: "simple and crude" },
    { word: "政府", pinyin: "zhèng fǔ", meaning: "government" },
    { word: "开辟", pinyin: "kāi pì", meaning: "to open up; pioneer" },
    { word: "优惠", pinyin: "yōu huì", meaning: "preferential; discount" },
    { word: "市镇", pinyin: "shì zhèn", meaning: "town; township" },
    { word: "宗教", pinyin: "zōng jiào", meaning: "religion" },
    { word: "综合", pinyin: "zōng hé", meaning: "comprehensive; integrate" },
    { word: "经济", pinyin: "jīng jì", meaning: "economy" },
    { word: "蓬勃", pinyin: "péng bó", meaning: "vigorous; flourishing" },
    { word: "富裕", pinyin: "fù yù", meaning: "prosperous; wealthy" },
    { word: "变迁", pinyin: "biàn qiān", meaning: "changes; transformation" },
    { word: "障碍", pinyin: "zhàng ài", meaning: "obstacle; barrier" },
    { word: "驰名", pinyin: "chí míng", meaning: "well-known; famous" },

    { word: "贸易", pinyin: "mào yì", meaning: "trade; commerce" },
    { word: "丝绸", pinyin: "sī chóu", meaning: "silk" },
    { word: "陆地", pinyin: "lù dì", meaning: "land; mainland" },
    { word: "瓷器", pinyin: "cí qì", meaning: "porcelain" },
    { word: "仪式", pinyin: "yí shì", meaning: "ceremony; ritual" },
    { word: "枢纽", pinyin: "shū niǔ", meaning: "hub; pivot" },
    { word: "港口", pinyin: "gǎng kǒu", meaning: "port; harbor" },
    { word: "传承", pinyin: "chuán chéng", meaning: "to inherit; pass on" },
    { word: "融合", pinyin: "róng hé", meaning: "mixture; fusion; harmonize" },
    { word: "勾勒", pinyin: "gōu lè", meaning: "to outline; sketch" },

    { word: "称赞", pinyin: "chēng zàn", meaning: "to praise" },
    { word: "崇拜", pinyin: "chóng bài", meaning: "to worship; adoration" },
    { word: "碰钉子", pinyin: "pèng dīng zi", meaning: "to meet with a rebuff" },
    { word: "泼冷水", pinyin: "pō lěng shuǐ", meaning: "to dampen enthusiasm" },
    { word: "抽屉", pinyin: "chōu ti", meaning: "drawer" },
    { word: "抑郁", pinyin: "yì yù", meaning: "depressed; gloomy" },
    { word: "沉默寡言", pinyin: "chén mò guǎ yán", meaning: "reticent; silent" },
    { word: "寂寞", pinyin: "jì mò", meaning: "lonely; lonesome" },
    { word: "懊恼", pinyin: "ào nǎo", meaning: "annoyed; vexed" },
    { word: "伺机", pinyin: "sì jī", meaning: "to wait for an opportunity" },
    { word: "打理", pinyin: "dǎ lǐ", meaning: "to manage; take care of" },
    { word: "家务", pinyin: "jiā wù", meaning: "household chores" },

    { word: "尤其", pinyin: "yóu qí", meaning: "especially" },
    { word: "愧疚", pinyin: "kuì jiù", meaning: "guilty; remorseful" },
    { word: "懒懒地", pinyin: "lǎn lǎn de", meaning: "lazily" },
    { word: "啾啾", pinyin: "jiū jiū", meaning: "chirping sound" },
    { word: "仰", pinyin: "yǎng", meaning: "to raise one's head; face upward" },
    { word: "凝望", pinyin: "níng wàng", meaning: "to gaze at" },
    { word: "鸟笼", pinyin: "niǎo lóng", meaning: "birdcage" },
    { word: "仿佛", pinyin: "fǎng fú", meaning: "to seem; as if" },
    { word: "愤怒", pinyin: "fèn nù", meaning: "angry; indignant" },
    { word: "喵", pinyin: "miāo", meaning: "meow" },
    { word: "衔", pinyin: "xián", meaning: "to hold in the mouth" },
    { word: "搞", pinyin: "gǎo", meaning: "to do; make" },
    { word: "辩解", pinyin: "biàn jiě", meaning: "to explain oneself; justify" },
    { word: "活泼", pinyin: "huó pō", meaning: "lively; active" },

    { word: "媒体", pinyin: "méi tǐ", meaning: "media" },
    { word: "塑料", pinyin: "sù liào", meaning: "plastic" },
    { word: "广泛", pinyin: "guǎng fàn", meaning: "wide-ranging; extensive" },
    { word: "吨", pinyin: "dūn", meaning: "ton" },
    { word: "廉价", pinyin: "lián jià", meaning: "cheap; inexpensive" },
    { word: "铺", pinyin: "pù", meaning: "shop; store" },
    { word: "污染", pinyin: "wū rǎn", meaning: "pollution; to pollute" },
    { word: "焚烧", pinyin: "fén shāo", meaning: "to burn" },
    { word: "烟尘", pinyin: "yān chén", meaning: "smoke and dust" },
    { word: "土壤", pinyin: "tǔ rǎng", meaning: "soil" },
    { word: "遏制", pinyin: "è zhì", meaning: "to curb; contain" },
    { word: "提供", pinyin: "tí gōng", meaning: "to provide" },
    { word: "倡导", pinyin: "chàng dǎo", meaning: "to advocate" },
    { word: "逐渐", pinyin: "zhú jiàn", meaning: "gradually" },

    { word: "委婉", pinyin: "wěi wǎn", meaning: "tactful; indirect" },
    { word: "彻底", pinyin: "chè dǐ", meaning: "thorough; complete" },
    { word: "缝", pinyin: "fèng", meaning: "crack; seam" },
    { word: "掩", pinyin: "yǎn", meaning: "to cover; hide" },
    { word: "恐惧", pinyin: "kǒng jù", meaning: "fear; dread" },
    { word: "走廊", pinyin: "zǒu láng", meaning: "corridor" },
    { word: "锁", pinyin: "suǒ", meaning: "lock" },
    { word: "熄灯", pinyin: "xī dēng", meaning: "lights out" },
    { word: "恐怖", pinyin: "kǒng bù", meaning: "horrifying; terrifying" },
    { word: "颤抖", pinyin: "chàn dǒu", meaning: "to tremble" },
    { word: "惊悚", pinyin: "jīng sǒng", meaning: "thrilling; horrifying" },
    { word: "和谐", pinyin: "hé xié", meaning: "harmonious" },
    { word: "冤家", pinyin: "yuān jiā", meaning: "enemy; quarrelsome couple" },
    { word: "误会", pinyin: "wù huì", meaning: "misunderstanding" },

    { word: "姿态", pinyin: "zī tài", meaning: "posture; stance" },
    { word: "翠绿", pinyin: "cuì lǜ", meaning: "jade green" },
    { word: "心旷神怡", pinyin: "xīn kuàng shén yí", meaning: "carefree and happy" },
    { word: "林荫", pinyin: "lín yīn", meaning: "shade of trees" },
    { word: "欣赏", pinyin: "xīn shǎng", meaning: "to appreciate" },
    { word: "粗糙", pinyin: "cū cāo", meaning: "coarse; rough" },
    { word: "撑", pinyin: "chēng", meaning: "to support; prop up" },
    { word: "同甘共苦", pinyin: "tóng gān gòng kǔ", meaning: "share hardships and joys together" },
    { word: "茁壮", pinyin: "zhuó zhuàng", meaning: "healthy and strong" },
    { word: "移民", pinyin: "yí mín", meaning: "immigrate" },
    { word: "接纳", pinyin: "jiē nà", meaning: "to accept" },
    { word: "无怨无悔", pinyin: "wú yuàn wú huǐ", meaning: "without complaint or regret" },
    { word: "千姿百态", pinyin: "qiān zī bǎi tài", meaning: "in many different forms" },
    { word: "空旷", pinyin: "kōng kuàng", meaning: "open and spacious" },

    { word: "岛屿", pinyin: "dǎo yǔ", meaning: "islands" },
    { word: "海峡", pinyin: "hǎi xiá", meaning: "strait" },
    { word: "历史", pinyin: "lì shǐ", meaning: "history" },
    { word: "区域", pinyin: "qū yù", meaning: "region; area" },
    { word: "汇集", pinyin: "huì jí", meaning: "to gather together" },
    { word: "给予", pinyin: "jǐ yǔ", meaning: "to give" },
    { word: "椰浆饭", pinyin: "yē jiāng fàn", meaning: "nasi lemak" },
    { word: "黄姜饭", pinyin: "huáng jiāng fàn", meaning: "turmeric rice" },
    { word: "发芽", pinyin: "fā yá", meaning: "to sprout" },
    { word: "新谣", pinyin: "xīn yáo", meaning: "Singapore Chinese songs" },
    { word: "瞩目", pinyin: "zhǔ mù", meaning: "to attract attention" },
    { word: "兼容并蓄", pinyin: "jiān róng bìng xù", meaning: "to assimilate all kinds of things" },
    { word: "求同存异", pinyin: "qiú tóng cún yì", meaning: "seek common ground while reserving differences" },

    { word: "严肃", pinyin: "yán sù", meaning: "serious; solemn" },
    { word: "解释", pinyin: "jiě shì", meaning: "to explain" },
    { word: "干脆", pinyin: "gān cuì", meaning: "straightforward; clear-cut" },
    { word: "风筝", pinyin: "fēng zhēng", meaning: "kite" },
    { word: "尴尬", pinyin: "gān gà", meaning: "awkward; embarrassed" },
    { word: "挣脱", pinyin: "zhèng tuō", meaning: "to break free" },
    { word: "惊讶", pinyin: "jīng yà", meaning: "surprised; astonished" },

    { word: "丰富", pinyin: "fēng fù", meaning: "rich; plentiful" },
    { word: "荒山", pinyin: "huāng shān", meaning: "barren hill" },
    { word: "褐", pinyin: "hè", meaning: "brown" },
    { word: "绕", pinyin: "rào", meaning: "to wind around" },
    { word: "丝毫", pinyin: "sī háo", meaning: "the slightest amount" },
    { word: "愣", pinyin: "lèng", meaning: "to stare blankly" },
    { word: "傻", pinyin: "shǎ", meaning: "foolish; silly" },
    { word: "急促", pinyin: "jí cù", meaning: "rapid; hurried" },

    { word: "选择", pinyin: "xuǎn zé", meaning: "to choose; choice" },
    { word: "寿命", pinyin: "shòu mìng", meaning: "lifespan" },
    { word: "缺乏", pinyin: "quē fá", meaning: "to lack" },
    { word: "再循环", pinyin: "zài xún huán", meaning: "recycling" },
    { word: "估计", pinyin: "gū jì", meaning: "to estimate" },

    { word: "脖子", pinyin: "bó zi", meaning: "neck" },
    { word: "社交媒体", pinyin: "shè jiāo méi tǐ", meaning: "social media" },
    { word: "缺陷", pinyin: "quē xiàn", meaning: "defect; flaw" },
    { word: "摄影", pinyin: "shè yǐng", meaning: "photography" },
    { word: "谷底", pinyin: "gǔ dǐ", meaning: "valley bottom; lowest point" },
    { word: "姿势", pinyin: "zī shì", meaning: "posture; pose" },
    { word: "模糊", pinyin: "mó hu", meaning: "blurred; vague" },
    { word: "掩饰", pinyin: "yǎn shì", meaning: "to conceal; cover up" },

    { word: "失智症", pinyin: "shī zhì zhèng", meaning: "dementia" },
    { word: "妻子", pinyin: "qī zi", meaning: "wife" },
    { word: "寻找", pinyin: "xún zhǎo", meaning: "to search for" },
    { word: "流逝", pinyin: "liú shì", meaning: "to pass by (time)" },
    { word: "嬉戏", pinyin: "xī xì", meaning: "to frolic; play" },
    { word: "咖喱卜", pinyin: "gā lí bo", meaning: "curry puff" },
    { word: "艘", pinyin: "sōu", meaning: "classifier for ships" },
    { word: "温馨", pinyin: "wēn xīn", meaning: "warm and affectionate" },
    { word: "鲜艳", pinyin: "xiān yàn", meaning: "bright-colored; vivid" },

    { word: "皇帝", pinyin: "huáng dì", meaning: "emperor" },
    { word: "典型", pinyin: "diǎn xíng", meaning: "typical; representative" },
    { word: "荒诞", pinyin: "huāng dàn", meaning: "absurd; ridiculous" },
    { word: "询问", pinyin: "xún wèn", meaning: "to inquire" },
    { word: "判断", pinyin: "pàn duàn", meaning: "to judge; judgment" },
    { word: "免疫", pinyin: "miǎn yì", meaning: "immune; immunity" },
    { word: "凝聚力", pinyin: "níng jù lì", meaning: "cohesion" },
    { word: "辨别", pinyin: "biàn bié", meaning: "to distinguish; differentiate" }
],

"Level 3": [
    { word: "良好", pinyin: "liáng hǎo", meaning: "good" },
    { word: "人际", pinyin: "rén jì", meaning: "human relationships" },
    { word: "坦率", pinyin: "tǎn shuài", meaning: "frank; candid" },
    { word: "隐瞒", pinyin: "yǐn mán", meaning: "to conceal; to hide" },
    { word: "粗鲁", pinyin: "cū lǔ", meaning: "rude; coarse" },
    { word: "分歧", pinyin: "fēn qí", meaning: "difference; disagreement" },
    { word: "妥协", pinyin: "tuǒ xié", meaning: "to compromise" },
    { word: "矛盾", pinyin: "máo dùn", meaning: "contradiction; conflict" },
    { word: "彼此", pinyin: "bǐ cǐ", meaning: "each other" },
    { word: "融洽", pinyin: "róng qià", meaning: "harmonious" },
    { word: "聆听", pinyin: "líng tīng", meaning: "to listen respectfully" },
    { word: "强迫", pinyin: "qiǎng pò", meaning: "to force" },

    { word: "蛋白质", pinyin: "dàn bái zhì", meaning: "protein" },
    { word: "蔬菜", pinyin: "shū cài", meaning: "vegetables" },
    { word: "全谷类", pinyin: "quán gǔ lèi", meaning: "whole grains" },
    { word: "麦片", pinyin: "mài piàn", meaning: "oatmeal; cereal flakes" },
    { word: "睡眠", pinyin: "shuì mián", meaning: "sleep" },
    { word: "频率", pinyin: "pín lǜ", meaning: "frequency" },
    { word: "敞开", pinyin: "chǎng kāi", meaning: "to open wide" },
    { word: "心扉", pinyin: "xīn fēi", meaning: "one's heart" },
    { word: "聊天", pinyin: "liáo tiān", meaning: "to chat" },
    { word: "淋漓", pinyin: "lín lí", meaning: "dripping wet; hearty" },
    { word: "绘画", pinyin: "huì huà", meaning: "painting; drawing" },
    { word: "抒发", pinyin: "shū fā", meaning: "to express emotions" },
    { word: "治愈", pinyin: "zhì yù", meaning: "to heal; to cure" },
    { word: "均衡", pinyin: "jūn héng", meaning: "balanced; equilibrium" },

    { word: "发掘", pinyin: "fā jué", meaning: "to discover; to unearth" },
    { word: "真挚", pinyin: "zhēn zhì", meaning: "sincere" },
    { word: "名额", pinyin: "míng é", meaning: "quota; place" },
    { word: "链接", pinyin: "liàn jiē", meaning: "link" },
    { word: "师傅", pinyin: "shī fu", meaning: "master; skilled worker" },
    { word: "裁缝", pinyin: "cái féng", meaning: "tailor" },
    { word: "编织", pinyin: "biān zhī", meaning: "to weave; to knit" },
    { word: "匠人", pinyin: "jiàng rén", meaning: "craftsman" },
    { word: "烘焙", pinyin: "hōng bèi", meaning: "to bake" },
    { word: "讲述", pinyin: "jiǎng shù", meaning: "to narrate; to tell" },
    { word: "黎明", pinyin: "lí míng", meaning: "dawn" },
    { word: "宵夜", pinyin: "xiāo yè", meaning: "late-night snack" },
    { word: "窍门", pinyin: "qiào mén", meaning: "knack; trick" },
    { word: "鲜为人知", pinyin: "xiǎn wéi rén zhī", meaning: "rarely known" },

    { word: "阐述", pinyin: "chǎn shù", meaning: "to elaborate; to explain" },
    { word: "清晰", pinyin: "qīng xī", meaning: "clear" },
    { word: "恰当", pinyin: "qià dàng", meaning: "appropriate; suitable" },
    { word: "肢体", pinyin: "zhī tǐ", meaning: "limbs; body" },
    { word: "僵硬", pinyin: "jiāng yìng", meaning: "stiff" },
    { word: "举手投足", pinyin: "jǔ shǒu tóu zú", meaning: "every gesture and movement" },
    { word: "啰嗦", pinyin: "luō suo", meaning: "long-winded" },
    { word: "筛选", pinyin: "shāi xuǎn", meaning: "to screen; to filter" },
    { word: "欲", pinyin: "yù", meaning: "desire; to want" },
    { word: "浏览", pinyin: "liú lǎn", meaning: "to browse" },
    { word: "培训", pinyin: "péi xùn", meaning: "training; to train" },
    { word: "沟通", pinyin: "gōu tōng", meaning: "to communicate" },

    { word: "涵盖", pinyin: "hán gài", meaning: "to cover; to include" },
    { word: "实践", pinyin: "shí jiàn", meaning: "to put into practice; practice" },
    { word: "亲戚", pinyin: "qīn qi", meaning: "relatives" },
    { word: "热忱", pinyin: "rè chén", meaning: "enthusiasm; zeal" },
    { word: "咨询", pinyin: "zī xún", meaning: "to consult" },
    { word: "逆水行舟", pinyin: "nì shuǐ xíng zhōu", meaning: "to row against the current" },
    { word: "淘汰", pinyin: "táo tài", meaning: "to eliminate" },
    { word: "分析", pinyin: "fēn xī", meaning: "to analyze" },
    { word: "数据", pinyin: "shù jù", meaning: "data" },
    { word: "枯燥", pinyin: "kū zào", meaning: "dry and dull" },
    { word: "震撼", pinyin: "zhèn hàn", meaning: "to shock; shock" },
    { word: "融会贯通", pinyin: "róng huì guàn tōng", meaning: "to integrate and master knowledge" },
    { word: "编写", pinyin: "biān xiě", meaning: "to compile; to write" },

    { word: "抛锚", pinyin: "pāo máo", meaning: "to break down; to anchor" },
    { word: "郁闷", pinyin: "yù mèn", meaning: "depressed; gloomy" },
    { word: "叼", pinyin: "diāo", meaning: "to hold in the mouth" },
    { word: "逗", pinyin: "dòu", meaning: "to tease; to amuse" },
    { word: "挑战", pinyin: "tiǎo zhàn", meaning: "challenge" },
    { word: "绊", pinyin: "bàn", meaning: "to trip" },
    { word: "攀登", pinyin: "pān dēng", meaning: "to climb" },
    { word: "山脉", pinyin: "shān mài", meaning: "mountain range" },
    { word: "宇宙", pinyin: "yǔ zhòu", meaning: "universe" },
    { word: "体验", pinyin: "tǐ yàn", meaning: "experience; to experience" },

    { word: "孤独", pinyin: "gū dú", meaning: "lonely; isolated" },
    { word: "清秀", pinyin: "qīng xiù", meaning: "delicate and pretty" },
    { word: "包扎", pinyin: "bāo zā", meaning: "to bandage" },
    { word: "缠", pinyin: "chán", meaning: "to wrap; to entangle" },
    { word: "纱布", pinyin: "shā bù", meaning: "gauze" },
    { word: "纯洁", pinyin: "chún jié", meaning: "pure" },
    { word: "默契", pinyin: "mò qì", meaning: "tacit understanding" },
    { word: "拒绝", pinyin: "jù jué", meaning: "to reject; to refuse" },
    { word: "犹豫", pinyin: "yóu yù", meaning: "to hesitate" },
    { word: "衡量", pinyin: "héng liáng", meaning: "to weigh; to measure" },
    { word: "由衷", pinyin: "yóu zhōng", meaning: "heartfelt; sincere" },
    { word: "流淌", pinyin: "liú tǎng", meaning: "to flow" },

    { word: "拖欠", pinyin: "tuō qiàn", meaning: "to owe; to be in arrears" },
    { word: "铅笔盒", pinyin: "qiān bǐ hé", meaning: "pencil case" },
    { word: "沮丧", pinyin: "jǔ sàng", meaning: "depressed; discouraged" },
    { word: "接触", pinyin: "jiē chù", meaning: "to contact; to touch" },
    { word: "曾经", pinyin: "céng jīng", meaning: "once; formerly" },
    { word: "家徒四壁", pinyin: "jiā tú sì bì", meaning: "extremely poor" },
    { word: "拘束", pinyin: "jū shù", meaning: "restrained; constrained" },
    { word: "步骤", pinyin: "bù zhòu", meaning: "steps; procedure" },
    { word: "厨艺", pinyin: "chú yì", meaning: "cooking skills" },
    { word: "规矩", pinyin: "guī ju", meaning: "rules; proper behavior" },
    { word: "拥有", pinyin: "yōng yǒu", meaning: "to possess; to have" },
    { word: "受益", pinyin: "shòu yì", meaning: "to benefit" },
    { word: "坦然", pinyin: "tǎn rán", meaning: "calm; composed" },

    { word: "援手", pinyin: "yuán shǒu", meaning: "helping hand; assistance" },
    { word: "侥幸", pinyin: "jiǎo xìng", meaning: "lucky; by chance" },
    { word: "慷慨解囊", pinyin: "kāng kǎi jiě náng", meaning: "to contribute generously" },
    { word: "渡", pinyin: "dù", meaning: "to cross; to tide over" },
    { word: "雪中送炭", pinyin: "xuě zhōng sòng tàn", meaning: "timely help" },
    { word: "和睦", pinyin: "hé mù", meaning: "harmonious; peaceful" },
    { word: "冷漠", pinyin: "lěng mò", meaning: "cold and indifferent" },
    { word: "挑剔", pinyin: "tiāo ti", meaning: "picky; fault-finding" },
    { word: "艰难", pinyin: "jiān nán", meaning: "difficult; hard" },
    { word: "营造", pinyin: "yíng zào", meaning: "to create; to build" },
    { word: "计较", pinyin: "jì jiào", meaning: "to fuss over; to haggle over" },

    { word: "润滑剂", pinyin: "rùn huá jì", meaning: "lubricant" },
    { word: "不胜枚举", pinyin: "bù shèng méi jǔ", meaning: "too numerous to list" },
    { word: "体恤", pinyin: "tǐ xù", meaning: "to show consideration; to empathize" },
    { word: "氛围", pinyin: "fēn wéi", meaning: "atmosphere; ambience" },
    { word: "所谓", pinyin: "suǒ wèi", meaning: "so-called" },
    { word: "谦虚", pinyin: "qiān xū", meaning: "modest; humble" },
    { word: "严峻", pinyin: "yán jùn", meaning: "severe; stern" },
    { word: "扰乱", pinyin: "rǎo luàn", meaning: "to disturb; to disrupt" },
    { word: "流言蜚语", pinyin: "liú yán fēi yǔ", meaning: "rumors and slanders" },
    { word: "畅谈", pinyin: "chàng tán", meaning: "to talk freely" },
    { word: "尊重", pinyin: "zūn zhòng", meaning: "to respect" },
    { word: "导致", pinyin: "dǎo zhì", meaning: "to lead to; to cause" },

    { word: "唐", pinyin: "táng", meaning: "Tang dynasty" },
    { word: "宋", pinyin: "sòng", meaning: "Song dynasty" },
    { word: "鼎盛", pinyin: "dǐng shèng", meaning: "peak period; flourishing" },
    { word: "柴", pinyin: "chái", meaning: "firewood" },
    { word: "醋", pinyin: "cù", meaning: "vinegar" },
    { word: "脱颖而出", pinyin: "tuō yǐng ér chū", meaning: "to stand out" },
    { word: "研发", pinyin: "yán fā", meaning: "research and development" },
    { word: "珍珠", pinyin: "zhēn zhū", meaning: "pearl" },
    { word: "熔化", pinyin: "róng huà", meaning: "to melt" },
    { word: "搅拌", pinyin: "jiǎo bàn", meaning: "to stir" },
    { word: "揉搓", pinyin: "róu cuō", meaning: "to rub; to knead" },
    { word: "消暑", pinyin: "xiāo shǔ", meaning: "to cool off" },
    { word: "五花八门", pinyin: "wǔ huā bā mén", meaning: "varied; all kinds of" },
    { word: "视频", pinyin: "shì pín", meaning: "video" },

    { word: "跋涉", pinyin: "bá shè", meaning: "to trek; to trudge" },
    { word: "牵挂", pinyin: "qiān guà", meaning: "to worry about; to miss" },
    { word: "唤", pinyin: "huàn", meaning: "to call" },
    { word: "喉咙", pinyin: "hóu lóng", meaning: "throat" },
    { word: "埋怨", pinyin: "mán yuàn", meaning: "to complain; to blame" },
    { word: "一般", pinyin: "yì bān", meaning: "ordinary; general" },
    { word: "无奈", pinyin: "wú nài", meaning: "helpless" },
    { word: "诧异", pinyin: "chà yì", meaning: "surprised; astonished" },
    { word: "贱", pinyin: "jiàn", meaning: "cheap; lowly" },
    { word: "眼眶", pinyin: "yǎn kuàng", meaning: "eye socket; rim of the eye" },
    { word: "探望", pinyin: "tàn wàng", meaning: "to visit" },
    { word: "咀嚼", pinyin: "jǔ jué", meaning: "to chew" },
    { word: "孝顺", pinyin: "xiào shùn", meaning: "filial" },
    { word: "谅解", pinyin: "liàng jiě", meaning: "to understand; to forgive" },

    { word: "矮", pinyin: "ǎi", meaning: "short" },
    { word: "患", pinyin: "huàn", meaning: "to suffer from" },
    { word: "开销", pinyin: "kāi xiāo", meaning: "expenses" },
    { word: "报刊", pinyin: "bào kān", meaning: "newspapers and magazines" },
    { word: "预知", pinyin: "yù zhī", meaning: "to foresee" },
    { word: "隆重", pinyin: "lóng zhòng", meaning: "grand; solemn" },

    { word: "苍白", pinyin: "cāng bái", meaning: "pale" },
    { word: "测验", pinyin: "cè yàn", meaning: "test; quiz" },
    { word: "锯子", pinyin: "jù zi", meaning: "saw" },
    { word: "书籍", pinyin: "shū jí", meaning: "books" },
    { word: "某", pinyin: "mǒu", meaning: "some; certain" },
    { word: "诅咒", pinyin: "zǔ zhòu", meaning: "to curse" },

    { word: "瑟瑟", pinyin: "sè sè", meaning: "shivering; rustling" },
    { word: "及格", pinyin: "jí gé", meaning: "to pass an exam" },
    { word: "偶尔", pinyin: "ǒu ěr", meaning: "occasionally" },
    { word: "传播", pinyin: "chuán bō", meaning: "to spread; to disseminate" },
    { word: "肿胀", pinyin: "zhǒng zhàng", meaning: "swollen; swelling" },
    { word: "幽静", pinyin: "yōu jìng", meaning: "quiet; secluded" },

    { word: "安抚", pinyin: "ān fǔ", meaning: "to comfort; to soothe" },
    { word: "步伐", pinyin: "bù fá", meaning: "pace; step" },
    { word: "遛", pinyin: "liù", meaning: "to stroll; to walk" },
    { word: "拨", pinyin: "bō", meaning: "to dial; to拨动" },
    { word: "敷", pinyin: "fū", meaning: "to apply; to spread on" },
    { word: "洋溢", pinyin: "yáng yì", meaning: "brimming with" },

    { word: "死党", pinyin: "sǐ dǎng", meaning: "best friends" },
    { word: "挫折", pinyin: "cuò zhé", meaning: "setback" },
    { word: "拴", pinyin: "shuān", meaning: "to tie; to fasten" },
    { word: "瞬间", pinyin: "shùn jiān", meaning: "in an instant" },
    { word: "绷带", pinyin: "bēng dài", meaning: "bandage" },
    { word: "演奏", pinyin: "yǎn zòu", meaning: "to perform music" },

    { word: "网络", pinyin: "wǎng luò", meaning: "network; internet" },
    { word: "基础", pinyin: "jī chǔ", meaning: "foundation; base" },
    { word: "踪影", pinyin: "zōng yǐng", meaning: "trace; sign" },
    { word: "弥补", pinyin: "mí bǔ", meaning: "to make up for" },
    { word: "普遍", pinyin: "pǔ biàn", meaning: "common; universal" },
    { word: "慈祥", pinyin: "cí xiáng", meaning: "kindly; benevolent" },

    { word: "逼", pinyin: "bī", meaning: "to force; to compel" },
    { word: "擅长", pinyin: "shàn cháng", meaning: "to be good at" },
    { word: "弊端", pinyin: "bì duān", meaning: "drawback; disadvantage" },
    { word: "屏幕", pinyin: "píng mù", meaning: "screen" },
    { word: "谨慎", pinyin: "jǐn shèn", meaning: "cautious; careful" },
    { word: "教授", pinyin: "jiào shòu", meaning: "professor" },

    { word: "筹划", pinyin: "chóu huà", meaning: "to plan; to prepare" },
    { word: "持之以恒", pinyin: "chí zhī yǐ héng", meaning: "to persevere" },
    { word: "划算", pinyin: "huá suàn", meaning: "worth it; cost-effective" },
    { word: "按钮", pinyin: "àn niǔ", meaning: "button" },
    { word: "割舍", pinyin: "gē shě", meaning: "to give up; to part with" },

    { word: "嫌弃", pinyin: "xián qì", meaning: "to dislike; to look down on" },
    { word: "符合", pinyin: "fú hé", meaning: "to conform to; to meet" },
    { word: "久而久之", pinyin: "jiǔ ér jiǔ zhī", meaning: "as time passes" },
    { word: "疆界", pinyin: "jiāng jiè", meaning: "boundary; border" },
    { word: "折磨", pinyin: "zhé mó", meaning: "to torment; suffering" },

    { word: "磨练", pinyin: "mó liàn", meaning: "to temper; to steel oneself" },
    { word: "庞大", pinyin: "páng dà", meaning: "huge; enormous" },
    { word: "介意", pinyin: "jiè yì", meaning: "to mind; to care about" },

    { word: "前所未有", pinyin: "qián suǒ wèi yǒu", meaning: "unprecedented" }
],

"Level 4": [
    { word: "观察", pinyin: "guān chá", meaning: "to observe" },
    { word: "敏捷", pinyin: "mǐn jié", meaning: "agile; quick" },
    { word: "爆发力", pinyin: "bào fā lì", meaning: "explosive power" },
    { word: "个性", pinyin: "gè xìng", meaning: "personality; individuality" },
    { word: "探险", pinyin: "tàn xiǎn", meaning: "to explore; adventure" },
    { word: "穿梭", pinyin: "chuān suō", meaning: "to shuttle back and forth" },
    { word: "遗漏", pinyin: "yí lòu", meaning: "to omit; to leave out" },
    { word: "掌握", pinyin: "zhǎng wò", meaning: "to master; to grasp" },
    { word: "泄气", pinyin: "xiè qì", meaning: "discouraged; to lose heart" },
    { word: "晋级", pinyin: "jìn jí", meaning: "to advance; promotion" },
    { word: "人云亦云", pinyin: "rén yún yì yún", meaning: "to echo others' opinions" },

    { word: "神圣", pinyin: "shén shèng", meaning: "sacred; holy" },
    { word: "痊愈", pinyin: "quán yù", meaning: "to recover completely" },
    { word: "继续", pinyin: "jì xù", meaning: "to continue" },
    { word: "拯救", pinyin: "zhěng jiù", meaning: "to save; to rescue" },
    { word: "煞费苦心", pinyin: "shà fèi kǔ xīn", meaning: "to take great pains" },
    { word: "渠道", pinyin: "qú dào", meaning: "channel; means" },
    { word: "天涯海角", pinyin: "tiān yá hǎi jiǎo", meaning: "the ends of the earth" },
    { word: "距离", pinyin: "jù lí", meaning: "distance" },
    { word: "遗憾", pinyin: "yí hàn", meaning: "regret; pity" },
    { word: "茫然", pinyin: "máng rán", meaning: "at a loss; blank" },
    { word: "遥远", pinyin: "yáo yuǎn", meaning: "distant; remote" },
    { word: "体魄", pinyin: "tǐ pò", meaning: "physique" },

    { word: "特殊", pinyin: "tè shū", meaning: "special" },
    { word: "饮料", pinyin: "yǐn liào", meaning: "beverage; drink" },
    { word: "族裔", pinyin: "zú yì", meaning: "ethnic group" },
    { word: "海纳百川", pinyin: "hǎi nà bǎi chuān", meaning: "to embrace diversity; broad-minded" },
    { word: "娘惹", pinyin: "niáng rě", meaning: "Nyonya" },
    { word: "时尚", pinyin: "shí shàng", meaning: "fashion; fashionable" },
    { word: "寓意", pinyin: "yù yì", meaning: "implied meaning; moral" },
    { word: "色泽", pinyin: "sè zé", meaning: "colour and lustre" },
    { word: "兆头", pinyin: "zhào tou", meaning: "omen; sign" },
    { word: "厄运", pinyin: "è yùn", meaning: "bad luck; misfortune" },
    { word: "携手", pinyin: "xié shǒu", meaning: "to join hands" },
    { word: "繁荣", pinyin: "fán róng", meaning: "prosperous; flourishing" },
    { word: "群策群力", pinyin: "qún cè qún lì", meaning: "to pool wisdom and efforts" },

    { word: "冰淇淋", pinyin: "bīng qí lín", meaning: "ice cream" },
    { word: "同侪", pinyin: "tóng chái", meaning: "peer" },
    { word: "撰写", pinyin: "zhuàn xiě", meaning: "to write; to compose" },
    { word: "募捐", pinyin: "mù juān", meaning: "to raise donations" },
    { word: "循规蹈矩", pinyin: "xún guī dǎo jǔ", meaning: "to follow rules strictly" },
    { word: "腼腆", pinyin: "miǎn tiǎn", meaning: "shy; bashful" },
    { word: "停止", pinyin: "tíng zhǐ", meaning: "to stop" },
    { word: "切磋", pinyin: "qiē cuō", meaning: "to exchange ideas; to learn from each other" },
    { word: "雕刻", pinyin: "diāo kè", meaning: "to carve; sculpture" },
    { word: "充实", pinyin: "chōng shí", meaning: "fulfilling; to enrich" },
    { word: "退休", pinyin: "tuì xiū", meaning: "to retire" },

    { word: "优雅", pinyin: "yōu yǎ", meaning: "elegant; graceful" },
    { word: "衰老", pinyin: "shuāi lǎo", meaning: "to age; aging" },
    { word: "旋转", pinyin: "xuán zhuǎn", meaning: "to rotate; to spin" },
    { word: "灌输", pinyin: "guàn shū", meaning: "to instill; to inculcate" },
    { word: "畏惧", pinyin: "wèi jù", meaning: "to fear; fear" },
    { word: "拓宽", pinyin: "tuò kuān", meaning: "to broaden; to widen" },
    { word: "辨认", pinyin: "biàn rèn", meaning: "to identify; to recognize" },
    { word: "措施", pinyin: "cuò shī", meaning: "measures; steps" },

    { word: "下棋", pinyin: "xià qí", meaning: "to play chess" },
    { word: "绞尽脑汁", pinyin: "jiǎo jìn nǎo zhī", meaning: "to rack one's brains" },
    { word: "胜券在握", pinyin: "shèng quàn zài wò", meaning: "to be sure of victory" },
    { word: "纷纷", pinyin: "fēn fēn", meaning: "one after another; in succession" },
    { word: "嚷", pinyin: "rǎng", meaning: "to shout; to yell" },
    { word: "不屑", pinyin: "bù xiè", meaning: "to disdain; to think beneath oneself" },
    { word: "享受", pinyin: "xiǎng shòu", meaning: "to enjoy" },
    { word: "启发", pinyin: "qǐ fā", meaning: "to inspire; to enlighten" },
    { word: "秉持", pinyin: "bǐng chí", meaning: "to uphold; to hold fast to" },
    { word: "汲取", pinyin: "jí qǔ", meaning: "to absorb; to draw from" },
    { word: "智慧", pinyin: "zhì huì", meaning: "wisdom" },
    { word: "裨益", pinyin: "bì yì", meaning: "benefit; advantage" },
    { word: "若有所思", pinyin: "ruò yǒu suǒ sī", meaning: "lost in thought" },
    { word: "在乎", pinyin: "zài hu", meaning: "to care about" },

    { word: "精疲力竭", pinyin: "jīng pí lì jié", meaning: "exhausted; worn out" },
    { word: "赋予", pinyin: "fù yǔ", meaning: "to give; to bestow" },
    { word: "嘈杂", pinyin: "cáo zá", meaning: "noisy; clamorous" },
    { word: "绽放", pinyin: "zhàn fàng", meaning: "to blossom; to bloom" },
    { word: "孜孜不倦", pinyin: "zī zī bù juàn", meaning: "diligent and tireless" },
    { word: "点燃", pinyin: "diǎn rán", meaning: "to ignite; to light" },
    { word: "答案", pinyin: "dá àn", meaning: "answer" },
    { word: "面面相觑", pinyin: "miàn miàn xiāng qù", meaning: "to look at one another in confusion" },
    { word: "残酷", pinyin: "cán kù", meaning: "cruel" },
    { word: "审视", pinyin: "shěn shì", meaning: "to examine carefully" },
    { word: "缓慢", pinyin: "huǎn màn", meaning: "slow" },
    { word: "目标", pinyin: "mù biāo", meaning: "goal; target" },

    { word: "芝麻", pinyin: "zhī ma", meaning: "sesame" },
    { word: "小贩", pinyin: "xiǎo fàn", meaning: "hawker; vendor" },
    { word: "颁发", pinyin: "bān fā", meaning: "to issue; to award" },
    { word: "雨后春笋", pinyin: "yǔ hòu chūn sǔn", meaning: "to spring up rapidly" },
    { word: "销声匿迹", pinyin: "xiāo shēng nì jì", meaning: "to disappear from sight" },
    { word: "年龄", pinyin: "nián líng", meaning: "age" },
    { word: "阶层", pinyin: "jiē céng", meaning: "social class; stratum" },
    { word: "摊位", pinyin: "tān wèi", meaning: "stall; booth" },
    { word: "奢侈", pinyin: "shē chǐ", meaning: "luxurious; extravagant" },
    { word: "遗产", pinyin: "yí chǎn", meaning: "heritage; legacy" },
    { word: "雀跃", pinyin: "què yuè", meaning: "to jump for joy" },
    { word: "品尝", pinyin: "pǐn cháng", meaning: "to taste; to sample" },

    { word: "雄鹰", pinyin: "xióng yīng", meaning: "eagle" },
    { word: "渺小", pinyin: "miǎo xiǎo", meaning: "tiny; insignificant" },
    { word: "有限", pinyin: "yǒu xiàn", meaning: "limited" },
    { word: "哲学", pinyin: "zhé xué", meaning: "philosophy" },
    { word: "过程", pinyin: "guò chéng", meaning: "process" },
    { word: "奥妙", pinyin: "ào miào", meaning: "mystery; subtlety" },
    { word: "辉煌", pinyin: "huī huáng", meaning: "splendid; glorious" },
    { word: "著名", pinyin: "zhù míng", meaning: "famous; renowned" },
    { word: "熟悉", pinyin: "shú xī", meaning: "familiar" },
    { word: "干涸", pinyin: "gān hé", meaning: "to dry up" },

    { word: "闹哄哄", pinyin: "nào hōng hōng", meaning: "noisy; bustling" },
    { word: "滥用", pinyin: "làn yòng", meaning: "to abuse; to misuse" },
    { word: "坐牢", pinyin: "zuò láo", meaning: "to be imprisoned" },
    { word: "靠拢", pinyin: "kào lǒng", meaning: "to draw close; to approach" },
    { word: "封", pinyin: "fēng", meaning: "to seal; classifier for letters" },
    { word: "是否", pinyin: "shì fǒu", meaning: "whether or not" },
    { word: "村子", pinyin: "cūn zi", meaning: "village" },
    { word: "耸立", pinyin: "sǒng lì", meaning: "to tower; to stand tall" },
    { word: "篱笆", pinyin: "lí ba", meaning: "fence" },

    { word: "风靡", pinyin: "fēng mǐ", meaning: "to be popular; fashionable" },
    { word: "崛起", pinyin: "jué qǐ", meaning: "to rise suddenly" },
    { word: "脾气", pinyin: "pí qi", meaning: "temper; disposition" },
    { word: "屡", pinyin: "lǚ", meaning: "repeatedly; frequently" },
    { word: "大显身手", pinyin: "dà xiǎn shēn shǒu", meaning: "to display one's skills fully" },
    { word: "胜仗", pinyin: "shèng zhàng", meaning: "victorious battle" },
    { word: "诀窍", pinyin: "jué qiào", meaning: "knack; trick" },
    { word: "岂", pinyin: "qǐ", meaning: "how could; rhetorical particle" },
    { word: "差劲", pinyin: "chà jìn", meaning: "poor; terrible" },
    { word: "匿名", pinyin: "nì míng", meaning: "anonymous" },
    { word: "自律", pinyin: "zì lǜ", meaning: "self-discipline" },
    { word: "咬牙切齿", pinyin: "yǎo yá qiè chǐ", meaning: "to gnash one's teeth in anger" },
    { word: "岗位", pinyin: "gǎng wèi", meaning: "post; position" },
    { word: "恍然大悟", pinyin: "huǎng rán dà wù", meaning: "to suddenly realize" },

    { word: "旅行", pinyin: "lǚ xíng", meaning: "to travel; travel" },
    { word: "租", pinyin: "zū", meaning: "to rent" },
    { word: "狭窄", pinyin: "xiá zhǎi", meaning: "narrow" },
    { word: "振振有词", pinyin: "zhèn zhèn yǒu cí", meaning: "to argue confidently" },
    { word: "抿", pinyin: "mǐn", meaning: "to purse one's lips" },
    { word: "嘴唇", pinyin: "zuǐ chún", meaning: "lips" },

    { word: "盛誉", pinyin: "shèng yù", meaning: "high reputation; great fame" },
    { word: "配方", pinyin: "pèi fāng", meaning: "formula; recipe" },
    { word: "家喻户晓", pinyin: "jiā yù hù xiǎo", meaning: "known to every household" },
    { word: "恶心", pinyin: "ě xin", meaning: "nauseous; disgusting" },
    { word: "肌肉", pinyin: "jī ròu", meaning: "muscle" },
    { word: "亚洲", pinyin: "yà zhōu", meaning: "Asia" },
    { word: "途径", pinyin: "tú jìng", meaning: "way; channel" },

    { word: "楷模", pinyin: "kǎi mó", meaning: "model; example" },
    { word: "敷衍", pinyin: "fū yǎn", meaning: "to do something perfunctorily" },
    { word: "佐证", pinyin: "zuǒ zhèng", meaning: "supporting evidence" },
    { word: "诗", pinyin: "shī", meaning: "poem; poetry" },
    { word: "平庸", pinyin: "píng yōng", meaning: "mediocre" },
    { word: "扼腕", pinyin: "è wàn", meaning: "to wring one's hands in regret" },
    { word: "探索", pinyin: "tàn suǒ", meaning: "to explore" },

    { word: "塞车", pinyin: "sāi chē", meaning: "traffic jam" },
    { word: "瑟缩", pinyin: "sè suō", meaning: "to shrink back; to cower" },
    { word: "雇主", pinyin: "gù zhǔ", meaning: "employer" },
    { word: "罐", pinyin: "guàn", meaning: "can; jar" },
    { word: "肋骨", pinyin: "lèi gǔ", meaning: "rib" },
    { word: "威胁", pinyin: "wēi xié", meaning: "threat; to threaten" },
    { word: "哽咽", pinyin: "gěng yè", meaning: "to choke with emotion" },
    { word: "遭遇", pinyin: "zāo yù", meaning: "to encounter; experience" }
]
};
