const vocabData = {
    "Level 1": [
    { word: "设施", pinyin: "shè shī", meaning: "facilities" },
    { word: "技能", pinyin: "jì néng", meaning: "skill; ability" },
    { word: "别扭", pinyin: "biè niu", meaning: "awkward; uncomfortable" },
    { word: "冤枉", pinyin: "yuān wang", meaning: "to accuse wrongly; treated unjustly" },
    { word: "锻炼", pinyin: "duàn liàn", meaning: "to exercise; to train" },
    { word: "科技", pinyin: "kē jì", meaning: "science and technology" },
    { word: "口头禅", pinyin: "kǒu tóu chán", meaning: "catchphrase; mantra" },
    { word: "小事一桩", pinyin: "xiǎo shì yī zhuāng", meaning: "a piece of cake" },
    { word: "人缘", pinyin: "rén yuán", meaning: "relations with other people" },
    { word: "推荐", pinyin: "tuī jiàn", meaning: "to recommend" },
    { word: "惹麻烦", pinyin: "rě má fan", meaning: "to cause trouble" },

    { word: "培养", pinyin: "péi yǎng", meaning: "to cultivate; to develop" },
    { word: "兴致勃勃", pinyin: "xìng zhì bó bó", meaning: "in high spirits; full of zest" },
    { word: "粘", pinyin: "zhān", meaning: "to glue; to paste; to stick to" },
    { word: "蛋液", pinyin: "dàn yè", meaning: "liquid of the egg" },
    { word: "狼狈", pinyin: "láng bèi", meaning: "in a difficult situation" },
    { word: "赌气", pinyin: "dǔ qì", meaning: "to act in a fit of pique" },
    { word: "小心翼翼", pinyin: "xiǎo xīn yì yì", meaning: "very carefully; prudent" },
    { word: "证明", pinyin: "zhèng míng", meaning: "to prove; proof" },
    { word: "捣乱", pinyin: "dǎo luàn", meaning: "to disturb; look for trouble" },
    { word: "荧光笔", pinyin: "yíng guāng bǐ", meaning: "highlighter" },
    { word: "抵挡", pinyin: "dǐ dǎng", meaning: "to resist; to ward off" },
    { word: "拉扯", pinyin: "lā che", meaning: "to drag; to pull; to raise a child" },
    { word: "手足无措", pinyin: "shǒu zú wú cuò", meaning: "at a loss to know what to do" },
    { word: "安慰", pinyin: "ān wèi", meaning: "to comfort; consolation" },
    { word: "布置", pinyin: "bù zhì", meaning: "to arrange; to assign" },
    { word: "随身", pinyin: "suí shēn", meaning: "to carry with oneself" },
    { word: "引起", pinyin: "yǐn qǐ", meaning: "to cause; to arouse" },

    { word: "究竟", pinyin: "jiū jìng", meaning: "after all; exactly" },
    { word: "虚惊一场", pinyin: "xū jīng yī chǎng", meaning: "a false alarm" },
    { word: "壮胆", pinyin: "zhuàng dǎn", meaning: "to bolster one's courage" },
    { word: "处理", pinyin: "chǔ lǐ", meaning: "to handle; to deal with" },
    { word: "关怀", pinyin: "guān huái", meaning: "care; concern" },

    { word: "习俗", pinyin: "xí sú", meaning: "custom; tradition" },
    { word: "辞旧迎新", pinyin: "cí jiù yíng xīn", meaning: "ring out the old and ring in the new" },
    { word: "玻璃", pinyin: "bō li", meaning: "glass" },
    { word: "柑", pinyin: "gān", meaning: "mandarin orange" },
    { word: "除夕", pinyin: "chú xī", meaning: "Chinese New Year's Eve" },
    { word: "财富", pinyin: "cái fù", meaning: "wealth; riches" },

    { word: "忙碌", pinyin: "máng lù", meaning: "busy; bustling" },
    { word: "装饰", pinyin: "zhuāng shì", meaning: "to decorate" },
    { word: "结婚", pinyin: "jié hūn", meaning: "to marry" },
    { word: "嫁", pinyin: "jià", meaning: "to marry (of a woman)" },
    { word: "匆匆", pinyin: "cōng cōng", meaning: "hurriedly; hastily" },
    { word: "碗碟", pinyin: "wǎn dié", meaning: "bowls and plates" },
    { word: "渐渐", pinyin: "jiàn jiàn", meaning: "gradually" },
    { word: "热腾腾", pinyin: "rè téng téng", meaning: "steaming hot" },
    { word: "象征", pinyin: "xiàng zhēng", meaning: "emblem; symbol" },
    { word: "围炉", pinyin: "wéi lú", meaning: "steamboat" },
    { word: "叽叽喳喳", pinyin: "jī jī zhā zhā", meaning: "chirp; chatter" },
    { word: "悦耳", pinyin: "yuè ěr", meaning: "sweet-sounding" },
    { word: "视讯", pinyin: "shì xùn", meaning: "video call" },
    { word: "期待", pinyin: "qī dài", meaning: "to look forward to; expectation" },

    { word: "红枣", pinyin: "hóng zǎo", meaning: "red date" },
    { word: "大吉大利", pinyin: "dà jí dà lì", meaning: "great luck and great prosperity" },
    { word: "疼爱", pinyin: "téng ài", meaning: "to love dearly" },
    { word: "儿媳妇", pinyin: "ér xí fu", meaning: "daughter-in-law" },
    { word: "感激", pinyin: "gǎn jī", meaning: "grateful; thankful" },
    { word: "莫名其妙", pinyin: "mò míng qí miào", meaning: "inexplicable; baffling" },
    { word: "疑惑", pinyin: "yí huò", meaning: "suspicion; to puzzle over" },
    { word: "喜悦", pinyin: "xǐ yuè", meaning: "joy; delight" },
    { word: "亲切", pinyin: "qīn qiè", meaning: "kind; friendly" },

    { word: "博物馆", pinyin: "bó wù guǎn", meaning: "museum" },
    { word: "收藏", pinyin: "shōu cáng", meaning: "to collect; collection" },
    { word: "建筑", pinyin: "jiàn zhù", meaning: "building; architecture" },
    { word: "巴刹", pinyin: "bā shā", meaning: "wet market" },
    { word: "售卖", pinyin: "shòu mài", meaning: "to sell" },
    { word: "皇宫", pinyin: "huáng gōng", meaning: "imperial palace" },
    { word: "城堡", pinyin: "chéng bǎo", meaning: "castle" },
    { word: "魅力", pinyin: "mèi lì", meaning: "charm; charisma" },
    { word: "流连忘返", pinyin: "liú lián wàng fǎn", meaning: "linger and forget to go home" },
    { word: "平均", pinyin: "píng jūn", meaning: "average" },
    { word: "繁忙", pinyin: "fán máng", meaning: "busy; bustling" },
    { word: "载客量", pinyin: "zài kè liàng", meaning: "passenger capacity" },
    { word: "娱乐", pinyin: "yú lè", meaning: "entertainment" },
    { word: "文化", pinyin: "wén huà", meaning: "culture" },

    { word: "横梁", pinyin: "héng liáng", meaning: "crossbeam" },
    { word: "覆盖", pinyin: "fù gài", meaning: "to cover" },
    { word: "瀑布", pinyin: "pù bù", meaning: "waterfall" },
    { word: "蹦跳", pinyin: "bèng tiào", meaning: "to hop; jump" },
    { word: "甚至", pinyin: "shèn zhì", meaning: "even" },
    { word: "刺激", pinyin: "cì jī", meaning: "exciting; to stimulate" },
    { word: "迷宫", pinyin: "mí gōng", meaning: "maze; labyrinth" },

    { word: "栏", pinyin: "lán", meaning: "fence; railing" },
    { word: "棕色", pinyin: "zōng sè", meaning: "brown" },
    { word: "氧化", pinyin: "yǎng huà", meaning: "oxidize" },
    { word: "即", pinyin: "jí", meaning: "namely; that is; immediately" },
    { word: "陌生", pinyin: "mò shēng", meaning: "strange; unfamiliar" },
    { word: "同胞", pinyin: "tóng bāo", meaning: "fellow citizen; compatriot" },
    { word: "宁静", pinyin: "níng jìng", meaning: "tranquil" },
    { word: "属于", pinyin: "shǔ yú", meaning: "belong to" },
    { word: "场景", pinyin: "chǎng jǐng", meaning: "scene; setting" },
    { word: "秘密", pinyin: "mì mì", meaning: "secret" },

    { word: "坚持不懈", pinyin: "jiān chí bù xiè", meaning: "persevere unremittingly" },
    { word: "诺言", pinyin: "nuò yán", meaning: "promise" },
    { word: "工作坊", pinyin: "gōng zuò fāng", meaning: "workshop" },
    { word: "维护", pinyin: "wéi hù", meaning: "safeguard; maintain" },
    { word: "友谊", pinyin: "yǒu yì", meaning: "friendship" },
    { word: "一帆风顺", pinyin: "yī fān fēng shùn", meaning: "smooth sailing" },
    { word: "有效", pinyin: "yǒu xiào", meaning: "effective; valid" },
    { word: "策略", pinyin: "cè lüè", meaning: "strategy" },
    { word: "嘉宾", pinyin: "jiā bīn", meaning: "esteemed guest" },
    { word: "辅导员", pinyin: "fǔ dǎo yuán", meaning: "counsellor" },
    { word: "言出必行", pinyin: "yán chū bì xíng", meaning: "to keep one's word" },
    { word: "以礼待人", pinyin: "yǐ lǐ dài rén", meaning: "treat with courtesy" },
    { word: "起码", pinyin: "qǐ mǎ", meaning: "at least; minimum" },

    { word: "早晨", pinyin: "zǎo chén", meaning: "early morning" },
    { word: "赖床", pinyin: "lài chuáng", meaning: "dawdle in bed" },
    { word: "滋味", pinyin: "zī wèi", meaning: "taste; flavor; feeling" },
    { word: "催促", pinyin: "cuī cù", meaning: "to urge" },
    { word: "哀求", pinyin: "āi qiú", meaning: "to plead" },
    { word: "硬着头皮", pinyin: "yìng zhe tou pí", meaning: "brace oneself to do something" },
    { word: "藤鞭", pinyin: "téng biān", meaning: "rattan cane" },
    { word: "挨打", pinyin: "ái dǎ", meaning: "take a beating" },
    { word: "混合", pinyin: "hùn hé", meaning: "to mix; mixture" },
    { word: "女佣", pinyin: "nǚ yōng", meaning: "maid" },
    { word: "嗓子眼", pinyin: "sǎng zi yǎn", meaning: "throat" },
    { word: "允许", pinyin: "yǔn xǔ", meaning: "permit; allow" },
    { word: "毛病", pinyin: "máo bìng", meaning: "fault; problem; bad habit" },
    { word: "逃学", pinyin: "táo xué", meaning: "to play truant; skip school" },
    { word: "居然", pinyin: "jū rán", meaning: "unexpectedly; actually" },

    { word: "相貌", pinyin: "xiàng mào", meaning: "appearance" },
    { word: "何必", pinyin: "hé bì", meaning: "why should; no need" },
    { word: "记账", pinyin: "jì zhàng", meaning: "bookkeeping" },
    { word: "亏", pinyin: "kuī", meaning: "deficit; deficiency" },
    { word: "撇", pinyin: "piē", meaning: "to cast away" },
    { word: "起航", pinyin: "qǐ háng", meaning: "set sail; take off" },
    { word: "治病", pinyin: "zhì bìng", meaning: "to treat an illness" },

    { word: "剩", pinyin: "shèng", meaning: "remain; left" },
    { word: "牙膏", pinyin: "yá gāo", meaning: "toothpaste" },
    { word: "橡皮擦", pinyin: "xiàng pí cā", meaning: "eraser" },
    { word: "薯条", pinyin: "shǔ tiáo", meaning: "french fries" },
    { word: "番茄酱", pinyin: "fān qié jiàng", meaning: "ketchup" },
    { word: "奖励", pinyin: "jiǎng lì", meaning: "reward" },
    { word: "获得", pinyin: "huò dé", meaning: "obtain; receive" },
    { word: "企业", pinyin: "qǐ yè", meaning: "enterprise; company" },
    { word: "创新", pinyin: "chuàng xīn", meaning: "innovation; to innovate" },

    { word: "牧场", pinyin: "mù chǎng", meaning: "pasture; ranch" },
    { word: "潜水", pinyin: "qián shuǐ", meaning: "to dive" },
    { word: "降落", pinyin: "jiàng luò", meaning: "to land; to descend" },
    { word: "屁股", pinyin: "pì gǔ", meaning: "buttocks" },
    { word: "翘", pinyin: "qiào", meaning: "stick up; tilt" },
    { word: "照耀", pinyin: "zhào yào", meaning: "to shine on; illuminate" },
    { word: "副", pinyin: "fù", meaning: "classifier for facial expressions" },
    { word: "浑身", pinyin: "hún shēn", meaning: "all over the body" },
    { word: "基因", pinyin: "jī yīn", meaning: "gene" },
    { word: "手势", pinyin: "shǒu shì", meaning: "gesture" },
    { word: "腾空而起", pinyin: "téng kōng ér qǐ", meaning: "to rise into the air" },
    { word: "打量", pinyin: "dǎ liang", meaning: "to size up; to look over" },

    { word: "伤脑筋", pinyin: "shāng nǎo jīn", meaning: "real headache" },
    { word: "拜访", pinyin: "bài fǎng", meaning: "to visit" },
    { word: "中央", pinyin: "zhōng yāng", meaning: "central" },
    { word: "漫步", pinyin: "màn bù", meaning: "wander; ramble" },
    { word: "华侨", pinyin: "huá qiáo", meaning: "overseas Chinese" },
    { word: "银行", pinyin: "yín háng", meaning: "bank" },
    { word: "摩天大楼", pinyin: "mó tiān dà lóu", meaning: "skyscraper" },
    { word: "薄薄的", pinyin: "báo báo de", meaning: "thin" },
    { word: "打交道", pinyin: "dǎ jiāo dào", meaning: "to deal with; to interact with" },

    { word: "油漆", pinyin: "yóu qī", meaning: "paint; lacquer" },
    { word: "栏杆", pinyin: "lán gān", meaning: "railing" },
    { word: "宿舍", pinyin: "sù shè", meaning: "dormitory" },
    { word: "凭", pinyin: "píng", meaning: "rely on" },
    { word: "订购", pinyin: "dìng gòu", meaning: "place an order" },
    { word: "塔台", pinyin: "tǎ tái", meaning: "control tower" },
    { word: "范围", pinyin: "fàn wéi", meaning: "range; scope" },
    { word: "警惕", pinyin: "jǐng tì", meaning: "vigilant; alert" },
    { word: "一旦", pinyin: "yī dàn", meaning: "once; in case" },
    { word: "失误", pinyin: "shī wù", meaning: "mistake" },
    { word: "不堪设想", pinyin: "bù kān shè xiǎng", meaning: "too horrible to contemplate" },
    { word: "及时", pinyin: "jí shí", meaning: "timely; in time" },
    { word: "心满意足", pinyin: "xīn mǎn yì zú", meaning: "perfectly contented; satisfied" },

    { word: "贡献", pinyin: "gòng xiàn", meaning: "contribute; contribution" },
    { word: "行驶", pinyin: "xíng shǐ", meaning: "travel; drive a vehicle" },
    { word: "延误", pinyin: "yán wu", meaning: "delay" },
    { word: "确保", pinyin: "què bǎo", meaning: "to ensure; to guarantee" },
    { word: "轨道", pinyin: "guǐ dào", meaning: "track; orbit" },
    { word: "凌晨", pinyin: "líng chén", meaning: "early morning" },
    { word: "就绪", pinyin: "jiù xù", meaning: "ready; in order" },
    { word: "裂痕", pinyin: "liè hén", meaning: "crack; split" },
    { word: "顺畅", pinyin: "shùn chàng", meaning: "fluent; smooth" },
    { word: "全力以赴", pinyin: "quán lì yǐ fù", meaning: "all-out effort" },
    { word: "职业", pinyin: "zhí yè", meaning: "occupation; profession" },
    { word: "故障", pinyin: "gù zhàng", meaning: "malfunction; fault" },
    { word: "幕后", pinyin: "mù hòu", meaning: "behind the scenes" },
    { word: "默默无闻", pinyin: "mò mò wú wén", meaning: "unknown; obscure; quietly working without fame" },
    { word: "维修", pinyin: "wéi xiū", meaning: "maintenance; repair" },

    { word: "隔壁", pinyin: "gé bì", meaning: "next door" },
    { word: "稳定", pinyin: "wěn dìng", meaning: "steady; stable" },
    { word: "光芒", pinyin: "guāng máng", meaning: "rays of light" },
    { word: "悠闲", pinyin: "yōu xián", meaning: "leisurely; carefree" },
    { word: "一辈子", pinyin: "yī bèi zi", meaning: "a lifetime; one's whole life" },
    { word: "奉献", pinyin: "fèng xiàn", meaning: "dedicate; devote" }
]
};
